import js from "@eslint/js";
import boundaries from "eslint-plugin-boundaries";
import jsdoc from "eslint-plugin-jsdoc";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import unicorn from "eslint-plugin-unicorn";
import eslintConfigPrettier from "eslint-config-prettier";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "src/metadata.ts", // generated by the @nestjs/swagger CLI plugin on every build
      "dist/**",
      "coverage/**",
      "node_modules/**",
      "*.config.mjs",
      "*.config.ts",
      ".husky/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  unicorn.configs.recommended,
  jsdoc.configs["flat/recommended-typescript-error"],
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "simple-import-sort": simpleImportSort,
      boundaries,
    },
    settings: {
      // Without a TS-aware resolver every import is "unknown" to
      // eslint-plugin-boundaries and the dependency rule silently never fires.
      "import/resolver": {
        typescript: { project: "./tsconfig.json", alwaysTryTypes: true },
      },
      "boundaries/elements": [
        { type: "config", pattern: "src/config/**" },
        { type: "common", pattern: "src/common/**" },
        { type: "integrations", pattern: "src/integrations/**" },
        { type: "modules", pattern: "src/modules/*", capture: ["module"] },
      ],
      // src/main.ts and src/app.module.ts are deliberately not elements: the
      // dependencies rule only judges imports made FROM an element.
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        {
          assertionStyle: "as",
          objectLiteralTypeAssertions: "never",
        },
      ],
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/explicit-member-accessibility": [
        "error",
        { overrides: { constructors: "no-public" } },
      ],
      "@typescript-eslint/explicit-function-return-type": [
        "error",
        { allowExpressions: true, allowTypedFunctionExpressions: true },
      ],
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true },
      ],
      "@typescript-eslint/no-extraneous-class": [
        "error",
        { allowWithDecorator: true },
      ],
      "@typescript-eslint/naming-convention": [
        "error",
        { selector: "default", format: ["camelCase"] },
        {
          selector: "variable",
          modifiers: ["const", "global"],
          format: ["camelCase", "UPPER_CASE", "PascalCase"],
        },
        { selector: "typeLike", format: ["PascalCase"] },
        { selector: "enumMember", format: ["UPPER_CASE"] },
        { selector: "objectLiteralProperty", format: null },
        { selector: "typeProperty", format: null },
        { selector: "import", format: null },
      ],
      "max-lines-per-function": [
        "error",
        { max: 40, skipBlankLines: true, skipComments: true },
      ],
      "max-lines": [
        "error",
        { max: 300, skipBlankLines: true, skipComments: true },
      ],
      complexity: ["error", 10],
      "max-depth": ["error", 3],
      "max-params": ["error", 4],
      "no-restricted-properties": [
        "error",
        {
          object: "process",
          property: "env",
          message:
            "Read configuration through AppConfigService; process.env is only read in src/config/env.schema.ts",
        },
      ],
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/index"],
              message: "No barrel files — import the concrete module directly.",
            },
            {
              group: ["**/helpers", "**/helpers/**"],
              message:
                "No helpers/ directories — use common/utils or a provider.",
            },
          ],
        },
      ],
      "no-console": "error",
      "no-warning-comments": [
        "error",
        { terms: ["todo", "fixme"], location: "start" },
      ],
      "boundaries/dependencies": [
        "error",
        {
          default: "disallow",
          policies: [
            {
              from: { element: { type: "config" } },
              allow: { to: { element: { type: "config" } } },
            },
            {
              from: { element: { type: "common" } },
              allow: { to: { element: { type: ["config", "common"] } } },
            },
            {
              from: { element: { type: "integrations" } },
              allow: {
                to: { element: { type: ["config", "common", "integrations"] } },
              },
            },
            {
              from: { element: { type: "modules" } },
              allow: {
                to: [
                  { element: { type: ["config", "common", "integrations"] } },
                  {
                    element: {
                      type: "modules",
                      captured: {
                        module: "{{ from.element.captured.module }}",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      ],
      "jsdoc/require-jsdoc": [
        "error",
        {
          publicOnly: true,
          contexts: [
            "TSTypeAliasDeclaration",
            "TSEnumDeclaration",
            "ExportNamedDeclaration > VariableDeclaration",
          ],
          require: {
            FunctionDeclaration: true,
            ClassDeclaration: true,
            MethodDefinition: true,
            ArrowFunctionExpression: true,
            FunctionExpression: true,
          },
        },
      ],
      "jsdoc/require-description": "error",
      "jsdoc/require-param": "error",
      "jsdoc/require-returns": "error",
      "jsdoc/require-param-type": "off",
      "jsdoc/require-returns-type": "off",
      "jsdoc/tag-lines": "off",
      "simple-import-sort/imports": [
        "error",
        {
          groups: [
            ["^node:"],
            ["^@?\\w"],
            ["^@/config", "^@/common", "^@/integrations"],
            ["^@/modules"],
            ["^\\."],
          ],
        },
      ],
      "simple-import-sort/exports": "error",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/no-null": "off",
      "unicorn/prefer-top-level-await": "off",
      "unicorn/prefer-module": "off",
      "unicorn/no-array-callback-reference": "off",
      "unicorn/no-array-reduce": "off",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
      // Deviation from spec: the recommended unicorn preset also enables these,
      // but they actively fight the required TSDoc/JSDoc style, the `env`
      // naming already used across the codebase, and Nest's own bootstrap
      // idiom (`bootstrap().catch(...)` + `process.exit(1)` in main.ts).
      "unicorn/name-replacements": "off",
      "unicorn/single-line-block-comment-style": "off",
      "unicorn/prefer-https": "off",
      "unicorn/no-negated-condition": "off",
      "unicorn/consistent-conditional-object-spread": "off",
      "unicorn/prefer-await": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/prefer-string-raw": "off",
    },
  },
  {
    files: ["**/*.module.ts"],
    rules: {
      "@typescript-eslint/no-extraneous-class": "off",
      "jsdoc/require-jsdoc": "off",
    },
  },
  {
    files: ["**/*.constants.ts"],
    rules: {
      "max-lines": "off",
    },
  },
  {
    files: ["**/*.spec.ts", "**/*.e2e-spec.ts", "test/**"],
    rules: {
      "max-lines-per-function": "off",
      "max-lines": "off",
      "jsdoc/require-jsdoc": "off",
      "@typescript-eslint/unbound-method": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  {
    files: ["scripts/**"],
    rules: {
      "no-console": "off",
    },
  },
  eslintConfigPrettier,
);
